export const ADD_WEATHER_LOCATION = 'ADD_WEATHER_LOCATION';
export const ADD_WEATHER_DATA_FROM_STORAGE = 'ADD_WEATHER_LOCATION';
export const REMOVE_WEATHER_LOCATION = 'REMOVE_WEATHER_LOCATION';

export const SET_LOCATION = 'USER_LOCATION';
export const UPDATE_LOCATION = 'USER_LOCATION';
